color_theme = "Default"
theme_background = False
truecolor = True

vim_keys = True
rounded_corners = True
show_battery = True
update_ms = 1500

proc_sorting = "cpu lazy"
proc_reversed = False
proc_tree = True
proc_colors = True

cpu_graph_upper = "total"
cpu_graph_lower = "total"
show_cpu_freq = True
check_temp = True

net_download = "10M"
net_upload = "10M"
