# # Status bar
set -g status-style bg=#B8D4B8,fg=#101007
#
# # Inactive window names
# set -g window-status-style fg=#9bc7b2,bg=#0d120f
# set -g window-status-format " #I:#W "
#
# # Active window name
# set -g window-status-current-style fg=#070a08,bg=#8cffb0,bold
# set -g window-status-current-format " #I:#W "
#
# # Separators
# set -g window-status-separator ""
#
# # Pane borders
# set -g pane-border-style fg=#5f7a6c
# set -g pane-active-border-style fg=#8cffb0
#
# # Messages
# set -g message-style bg=#131915,fg=#d7fbe8
#
# # Left / right
# set -g status-left " #[fg=#0d120f,bold]#S #[default]"
# set -g status-right "#[fg=#d7fbe8]%H:%M #[fg=#9bc7b2]%Y-%m-%d "

unbind r
bind r source-file ~/.tmux.conf \; display-message "Config reloaded!"

set -g default-terminal "screen-256color"
set -g base-index 1
set -g pane-base-index 1
set-option -g renumber-windows on
set-option -g mouse on

unbind C-b
set -g prefix C-v
bind C-v send-prefix

# unbind C-b
# set -g prefix §
# bind § send-prefix

bind | split-window -h
bind - split-window -v

unbind C-j
unbind C-n
# change session with prefix + j
bind C-j display-popup -E "tmux list-sessions | sed -E 's/:.*$//' | grep -v \"^$(tmux display-message -p '#S')\$\" | fzf --reverse | xargs tmux switch-client -t"
bind C-n display-popup -E 'bash -i -c "read -p \"Session name: \" name; tmux new-session -d -s \$name && tmux switch-client -t \$name"'

# pane navigation
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# change pane size - use prefix followed by J,K,L,H
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5
